# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: About
    url: /#about
    weight: 10
  - name: Program (TBD)
    url: /#program
    weight: 20
  - name: Venue
    url: /#venue
    weight: 30
  - name: Gallery
    url: /#gallery
    weight: 40
  - name: People
    url: /#people
    weight: 50
  - name: Sponsors
    url: /#sponsor
    weight: 60
