# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  # mode: light
  color: sky

# # SEO
# marketing:
#   seo:
#     site_type: Person
#     local_business_type: ''
#     org_name: ''
#     description: 'A highly-customizable Hugo landing page theme powered by Hugo Blox website builder.'
#     twitter: 'GetResearchDev'
#   analytics:
#     google_analytics: ''
#     baidu_tongji: ''
#     plausible: ''
#     fathom: ''
#     pirsch: ''
#   verification:
#     google: ''
#     baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "Pre-CHI 2025"
      # Logo filename in `assets/media/` folder
      filename: 
        light_mode: "gba-logo.svg"
        dark_mode: "gba-logo-dark-mode.svg"
    button:
      enable: true
      text: "Register Now"
      url: "https://bespoke-profiterole-9c46e8.netlify.app/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  block: custom
  copyright:
    notice: '© {year} Greater Bay HCI | 粤港澳大湾区人机交互论坛'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

features:
  comment:
    # Choose a provider: giscus, disqus, commento, or '' to disable commenting
    provider: 'comentario'
    comentario:
      url: 'https://csz196.cse.ust.hk/prechi/comentario/en'
      css: "css/themes/comentario.css"
